DEVICE: cuda

MODEL:
  SPLIT_SIZE: 7
  NUM_BOXES: 2
  NUM_CLASSES: 10

TRAIN:
  LEARNING_RATE: 0.001
  NUM_EPOCH: 100
  BATCH_SIZE: 16

INFERENCE:
  CONFIDENCE_THRESHOLD: 0.2
  IOU_THRESHOLD: 0.5

LOSS:
  LAMBDA_COORD: 5
  LAMBDA_NOOBJ: 0.5

DATASET:
  PATH: './data/Drink_284_Detection'
